const ADJECTIVES = [
  'swift',
  'bold',
  'calm',
  'daring',
  'eager',
  'fresh',
  'glowing',
  'lively',
  'mighty',
  'radiant',
  'brisk',
  'steady',
  'vibrant',
  'quiet',
  'bright',
  'clever',
  'gentle',
  'keen',
  'nimble',
  'resolute',
  'spirited',
  'sunny',
  'thriving',
  'valiant',
  'witty',
  'brave',
  'elevated',
  'focused',
  'golden',
  'humble',
  'lucky',
  'serene',
  'tender',
  'vivid',
  'zesty',
  'cool',
  'driven',
  'evergreen',
  'gallant',
  'kind',
];

const NOUNS = [
  'lion',
  'falcon',
  'otter',
  'orca',
  'panther',
  'sparrow',
  'walrus',
  'willow',
  'juniper',
  'ember',
  'fox',
  'raven',
  'wolf',
  'owl',
  'bear',
  'tiger',
  'eagle',
  'whale',
  'salmon',
  'lynx',
  'cedar',
  'maple',
  'canyon',
  'harbor',
  'ridge',
  'meadow',
  'comet',
  'river',
  'brook',
  'glade',
  'bison',
  'badger',
  'puma',
  'sable',
  'heron',
  'prairie',
  'summit',
  'trail',
  'horizon',
  'atlas',
];

export function generateUsername(suffixDigits = 4): string {
  const adjective = ADJECTIVES[Math.floor(Math.random() * ADJECTIVES.length)];
  const noun = NOUNS[Math.floor(Math.random() * NOUNS.length)];
  const suffix = Math.floor(Math.random() * Math.pow(10, suffixDigits))
    .toString()
    .padStart(suffixDigits, '0');
  return `${adjective}-${noun}-${suffix}`;
}
