import { MigrationInterface, QueryRunner } from "typeorm";

export class Migrations1764965534316 implements MigrationInterface {
    name = 'Migrations1764965534316'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "core"."customer_profiles" DROP CONSTRAINT "customer_profiles_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "core"."favorite_stores" DROP CONSTRAINT "FK_favorite_store_user"`);
        await queryRunner.query(`ALTER TABLE "core"."reviews" DROP CONSTRAINT "reviews_store_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "core"."reviews" DROP CONSTRAINT "reviews_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "core"."hormone_logs" DROP CONSTRAINT "hormone_logs_customer_profile_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "billing"."billing_customers" DROP CONSTRAINT "billing_customers_vendor_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "billing"."billing_invoices" DROP CONSTRAINT "billing_invoices_billing_subscription_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "billing"."billing_invoices" DROP CONSTRAINT "billing_invoices_vendor_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "billing"."billing_subscription_items" DROP CONSTRAINT "billing_subscription_items_billing_subscription_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "billing"."billing_subscription_items" DROP CONSTRAINT "billing_subscription_items_vendor_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "billing"."billing_subscriptions" DROP CONSTRAINT "billing_subscriptions_billing_customer_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "billing"."billing_subscriptions" DROP CONSTRAINT "billing_subscriptions_plan_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "billing"."billing_subscriptions" DROP CONSTRAINT "billing_subscriptions_vendor_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "analytics"."analytics_events" DROP CONSTRAINT "analytics_events_product_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "analytics"."analytics_events" DROP CONSTRAINT "analytics_events_store_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "analytics"."analytics_events" DROP CONSTRAINT "analytics_events_vendor_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "core"."product_category_links" DROP CONSTRAINT "product_category_links_category_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "core"."product_category_links" DROP CONSTRAINT "product_category_links_product_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "core"."review_tag_links" DROP CONSTRAINT "review_tag_links_review_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "core"."review_tag_links" DROP CONSTRAINT "review_tag_links_tag_id_fkey"`);
        await queryRunner.query(`DROP INDEX "core"."idx_reviews_store_user"`);
        await queryRunner.query(`DROP INDEX "core"."idx_reviews_store_id"`);
        await queryRunner.query(`DROP INDEX "core"."idx_reviews_status"`);
        await queryRunner.query(`DROP INDEX "core"."idx_stores_coordinates_gix"`);
        await queryRunner.query(`DROP INDEX "core"."idx_hormone_logs_profile_date"`);
        await queryRunner.query(`DROP INDEX "billing"."idx_billing_webhook_events_type"`);
        await queryRunner.query(`DROP INDEX "billing"."idx_billing_customers_vendor_id"`);
        await queryRunner.query(`DROP INDEX "billing"."idx_billing_invoices_vendor_id"`);
        await queryRunner.query(`DROP INDEX "billing"."idx_billing_invoices_subscription_id"`);
        await queryRunner.query(`DROP INDEX "billing"."idx_billing_subscription_items_subscription_id"`);
        await queryRunner.query(`DROP INDEX "billing"."idx_billing_subscription_items_price_id"`);
        await queryRunner.query(`DROP INDEX "billing"."idx_billing_subscription_items_vendor_id"`);
        await queryRunner.query(`DROP INDEX "billing"."idx_billing_subscription_items_subscription_price"`);
        await queryRunner.query(`DROP INDEX "billing"."idx_billing_subscriptions_vendor_id"`);
        await queryRunner.query(`DROP INDEX "billing"."idx_billing_subscriptions_plan_id"`);
        await queryRunner.query(`DROP INDEX "billing"."idx_billing_subscriptions_billing_customer_id"`);
        await queryRunner.query(`DROP INDEX "analytics"."idx_analytics_events_store_date"`);
        await queryRunner.query(`DROP INDEX "analytics"."idx_analytics_events_vendor_date"`);
        await queryRunner.query(`DROP INDEX "analytics"."idx_analytics_events_type_date"`);
        await queryRunner.query(`ALTER TABLE "core"."reviews" DROP CONSTRAINT "reviews_rating_check"`);
        await queryRunner.query(`ALTER TABLE "core"."hormone_logs" DROP CONSTRAINT "hormone_logs_form_factor_check"`);
        await queryRunner.query(`ALTER TABLE "core"."hormone_logs" DROP CONSTRAINT "hormone_logs_mood_score_check"`);
        await queryRunner.query(`ALTER TABLE "billing"."billing_plans" DROP CONSTRAINT "billing_plans_interval_check"`);
        await queryRunner.query(`ALTER TABLE "billing"."billing_subscriptions" DROP CONSTRAINT "billing_subscriptions_status_check"`);
        await queryRunner.query(`ALTER TABLE "analytics"."analytics_events" DROP CONSTRAINT "analytics_events_type_check"`);
        await queryRunner.query(`ALTER TABLE "core"."products" ADD "unit_count" integer`);
        await queryRunner.query(`ALTER TABLE "core"."products" ADD "unit_count_type" text`);
        await queryRunner.query(`ALTER TABLE "core"."products" ADD "form_factor" text`);
        await queryRunner.query(`ALTER TABLE "core"."products" ADD "billing_type" text NOT NULL DEFAULT 'one_time'`);
        await queryRunner.query(`ALTER TABLE "core"."products" ADD "billing_interval" text`);
        await queryRunner.query(`ALTER TABLE "core"."products" ADD "billing_quantity" integer NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "core"."stores" DROP COLUMN "coordinates"`);
        await queryRunner.query(`DELETE FROM "typeorm_metadata" WHERE "type" = $1 AND "name" = $2 AND "database" = $3 AND "schema" = $4 AND "table" = $5`, ["GENERATED_COLUMN","coordinates","postgres","core","stores"]);
        await queryRunner.query(`ALTER TABLE "core"."stores" ADD "coordinates" geography(Point,4326) GENERATED ALWAYS AS (CASE WHEN latitude IS NOT NULL AND longitude IS NOT NULL THEN ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography END) STORED`);
        await queryRunner.query(`INSERT INTO "typeorm_metadata"("database", "schema", "table", "type", "name", "value") VALUES ($1, $2, $3, $4, $5, $6)`, ["postgres","core","stores","GENERATED_COLUMN","coordinates","CASE WHEN latitude IS NOT NULL AND longitude IS NOT NULL THEN ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography END"]);
        await queryRunner.query(`ALTER TABLE "core"."hormone_logs" ALTER COLUMN "date_taken" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "billing"."billing_webhook_events" DROP CONSTRAINT "billing_webhook_events_stripe_event_id_key"`);
        await queryRunner.query(`ALTER TABLE "billing"."billing_customers" DROP CONSTRAINT "billing_customers_stripe_customer_id_key"`);
        await queryRunner.query(`ALTER TABLE "billing"."billing_plans" DROP CONSTRAINT "billing_plans_key_key"`);
        await queryRunner.query(`ALTER TABLE "billing"."billing_plans" DROP CONSTRAINT "billing_plans_stripe_price_id_key"`);
        await queryRunner.query(`ALTER TABLE "billing"."billing_invoices" DROP CONSTRAINT "billing_invoices_stripe_invoice_id_key"`);
        await queryRunner.query(`ALTER TABLE "billing"."billing_subscriptions" DROP CONSTRAINT "billing_subscriptions_stripe_subscription_id_key"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_21407014545ef0c45a88490f74" ON "core"."reviews" ("store_id", "user_id") WHERE "deleted_at" IS NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_hormone_logs_profile_date" ON "core"."hormone_logs" ("customer_profile_id", "date_taken") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e15138e01ce353a3c125dca00c" ON "billing"."billing_webhook_events" ("stripe_event_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8236710a5135642b2311310209" ON "billing"."billing_customers" ("stripe_customer_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_54563a33b48ebab323572134f0" ON "billing"."billing_plans" ("key") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5b0d3b9f7662f0dcb6d5341a8f" ON "billing"."billing_plans" ("stripe_price_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_67e126e24f07c0e4992f60d0ca" ON "billing"."billing_invoices" ("stripe_invoice_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_billing_subscription_item_subscription_price" ON "billing"."billing_subscription_items" ("billing_subscription_id", "stripe_price_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_477e29a06a5144238e8c06f419" ON "billing"."billing_subscriptions" ("stripe_subscription_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_fbae56b0260cafe5887957c94e" ON "analytics"."analytics_events" ("store_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f751390992a3f57a7a3d05d886" ON "analytics"."analytics_events" ("vendor_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a80d4c8a9c216ed6647a8e8f38" ON "analytics"."analytics_events" ("product_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bf04c83c15a231f0cf00c5110c" ON "analytics"."analytics_events" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_2c2389b9646e38a132707f9a49" ON "analytics"."analytics_events" ("occurred_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_a108ea5e3a037ff68cc5081866" ON "core"."product_category_links" ("product_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_6a244b8fec3db8a3ce4b8c797e" ON "core"."product_category_links" ("category_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1819413b8314b64f6e927c4ea7" ON "core"."review_tag_links" ("review_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_509b2335fb53da3314ae3e0acd" ON "core"."review_tag_links" ("tag_id") `);
        await queryRunner.query(`ALTER TABLE "core"."customer_profiles" ADD CONSTRAINT "FK_99617dd6d452ad43dd992a79933" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."favorite_stores" ADD CONSTRAINT "FK_56fb8d1c2957b914f08122db7d6" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."reviews" ADD CONSTRAINT "FK_53d569324f429e5d3af161f1657" FOREIGN KEY ("store_id") REFERENCES "core"."stores"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."reviews" ADD CONSTRAINT "FK_728447781a30bc3fcfe5c2f1cdf" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."hormone_logs" ADD CONSTRAINT "FK_0c7caf70808cd77ee58f7eb3458" FOREIGN KEY ("customer_profile_id") REFERENCES "core"."customer_profiles"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "billing"."billing_customers" ADD CONSTRAINT "FK_0939e6bde0d0cd428d01c00d788" FOREIGN KEY ("vendor_id") REFERENCES "core"."vendors"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "billing"."billing_invoices" ADD CONSTRAINT "FK_2d7a6671d1c6d403502643690bf" FOREIGN KEY ("vendor_id") REFERENCES "core"."vendors"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "billing"."billing_invoices" ADD CONSTRAINT "FK_80c8784a1056da82574fda5a5b9" FOREIGN KEY ("billing_subscription_id") REFERENCES "billing"."billing_subscriptions"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "billing"."billing_subscription_items" ADD CONSTRAINT "FK_72618d620b74bcb0110555156eb" FOREIGN KEY ("billing_subscription_id") REFERENCES "billing"."billing_subscriptions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "billing"."billing_subscription_items" ADD CONSTRAINT "FK_0f0d2435f8a24d45b343f0c2224" FOREIGN KEY ("vendor_id") REFERENCES "core"."vendors"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "billing"."billing_subscriptions" ADD CONSTRAINT "FK_e853a0a6458d5919741e631da90" FOREIGN KEY ("vendor_id") REFERENCES "core"."vendors"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "billing"."billing_subscriptions" ADD CONSTRAINT "FK_b41d4b1ebaa27c734d3806995ea" FOREIGN KEY ("billing_customer_id") REFERENCES "billing"."billing_customers"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "billing"."billing_subscriptions" ADD CONSTRAINT "FK_d392143a6910ee9948715148b0a" FOREIGN KEY ("plan_id") REFERENCES "billing"."billing_plans"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."product_category_links" ADD CONSTRAINT "FK_a108ea5e3a037ff68cc50818665" FOREIGN KEY ("product_id") REFERENCES "core"."products"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "core"."product_category_links" ADD CONSTRAINT "FK_6a244b8fec3db8a3ce4b8c797e5" FOREIGN KEY ("category_id") REFERENCES "core"."product_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."review_tag_links" ADD CONSTRAINT "FK_1819413b8314b64f6e927c4ea79" FOREIGN KEY ("review_id") REFERENCES "core"."reviews"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "core"."review_tag_links" ADD CONSTRAINT "FK_509b2335fb53da3314ae3e0acd3" FOREIGN KEY ("tag_id") REFERENCES "core"."review_tags"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "core"."review_tag_links" DROP CONSTRAINT "FK_509b2335fb53da3314ae3e0acd3"`);
        await queryRunner.query(`ALTER TABLE "core"."review_tag_links" DROP CONSTRAINT "FK_1819413b8314b64f6e927c4ea79"`);
        await queryRunner.query(`ALTER TABLE "core"."product_category_links" DROP CONSTRAINT "FK_6a244b8fec3db8a3ce4b8c797e5"`);
        await queryRunner.query(`ALTER TABLE "core"."product_category_links" DROP CONSTRAINT "FK_a108ea5e3a037ff68cc50818665"`);
        await queryRunner.query(`ALTER TABLE "billing"."billing_subscriptions" DROP CONSTRAINT "FK_d392143a6910ee9948715148b0a"`);
        await queryRunner.query(`ALTER TABLE "billing"."billing_subscriptions" DROP CONSTRAINT "FK_b41d4b1ebaa27c734d3806995ea"`);
        await queryRunner.query(`ALTER TABLE "billing"."billing_subscriptions" DROP CONSTRAINT "FK_e853a0a6458d5919741e631da90"`);
        await queryRunner.query(`ALTER TABLE "billing"."billing_subscription_items" DROP CONSTRAINT "FK_0f0d2435f8a24d45b343f0c2224"`);
        await queryRunner.query(`ALTER TABLE "billing"."billing_subscription_items" DROP CONSTRAINT "FK_72618d620b74bcb0110555156eb"`);
        await queryRunner.query(`ALTER TABLE "billing"."billing_invoices" DROP CONSTRAINT "FK_80c8784a1056da82574fda5a5b9"`);
        await queryRunner.query(`ALTER TABLE "billing"."billing_invoices" DROP CONSTRAINT "FK_2d7a6671d1c6d403502643690bf"`);
        await queryRunner.query(`ALTER TABLE "billing"."billing_customers" DROP CONSTRAINT "FK_0939e6bde0d0cd428d01c00d788"`);
        await queryRunner.query(`ALTER TABLE "core"."hormone_logs" DROP CONSTRAINT "FK_0c7caf70808cd77ee58f7eb3458"`);
        await queryRunner.query(`ALTER TABLE "core"."reviews" DROP CONSTRAINT "FK_728447781a30bc3fcfe5c2f1cdf"`);
        await queryRunner.query(`ALTER TABLE "core"."reviews" DROP CONSTRAINT "FK_53d569324f429e5d3af161f1657"`);
        await queryRunner.query(`ALTER TABLE "core"."favorite_stores" DROP CONSTRAINT "FK_56fb8d1c2957b914f08122db7d6"`);
        await queryRunner.query(`ALTER TABLE "core"."customer_profiles" DROP CONSTRAINT "FK_99617dd6d452ad43dd992a79933"`);
        await queryRunner.query(`DROP INDEX "core"."IDX_509b2335fb53da3314ae3e0acd"`);
        await queryRunner.query(`DROP INDEX "core"."IDX_1819413b8314b64f6e927c4ea7"`);
        await queryRunner.query(`DROP INDEX "core"."IDX_6a244b8fec3db8a3ce4b8c797e"`);
        await queryRunner.query(`DROP INDEX "core"."IDX_a108ea5e3a037ff68cc5081866"`);
        await queryRunner.query(`DROP INDEX "analytics"."IDX_2c2389b9646e38a132707f9a49"`);
        await queryRunner.query(`DROP INDEX "analytics"."IDX_bf04c83c15a231f0cf00c5110c"`);
        await queryRunner.query(`DROP INDEX "analytics"."IDX_a80d4c8a9c216ed6647a8e8f38"`);
        await queryRunner.query(`DROP INDEX "analytics"."IDX_f751390992a3f57a7a3d05d886"`);
        await queryRunner.query(`DROP INDEX "analytics"."IDX_fbae56b0260cafe5887957c94e"`);
        await queryRunner.query(`DROP INDEX "billing"."IDX_477e29a06a5144238e8c06f419"`);
        await queryRunner.query(`DROP INDEX "billing"."IDX_billing_subscription_item_subscription_price"`);
        await queryRunner.query(`DROP INDEX "billing"."IDX_67e126e24f07c0e4992f60d0ca"`);
        await queryRunner.query(`DROP INDEX "billing"."IDX_5b0d3b9f7662f0dcb6d5341a8f"`);
        await queryRunner.query(`DROP INDEX "billing"."IDX_54563a33b48ebab323572134f0"`);
        await queryRunner.query(`DROP INDEX "billing"."IDX_8236710a5135642b2311310209"`);
        await queryRunner.query(`DROP INDEX "billing"."IDX_e15138e01ce353a3c125dca00c"`);
        await queryRunner.query(`DROP INDEX "core"."IDX_hormone_logs_profile_date"`);
        await queryRunner.query(`DROP INDEX "core"."IDX_21407014545ef0c45a88490f74"`);
        await queryRunner.query(`ALTER TABLE "billing"."billing_subscriptions" ADD CONSTRAINT "billing_subscriptions_stripe_subscription_id_key" UNIQUE ("stripe_subscription_id")`);
        await queryRunner.query(`ALTER TABLE "billing"."billing_invoices" ADD CONSTRAINT "billing_invoices_stripe_invoice_id_key" UNIQUE ("stripe_invoice_id")`);
        await queryRunner.query(`ALTER TABLE "billing"."billing_plans" ADD CONSTRAINT "billing_plans_stripe_price_id_key" UNIQUE ("stripe_price_id")`);
        await queryRunner.query(`ALTER TABLE "billing"."billing_plans" ADD CONSTRAINT "billing_plans_key_key" UNIQUE ("key")`);
        await queryRunner.query(`ALTER TABLE "billing"."billing_customers" ADD CONSTRAINT "billing_customers_stripe_customer_id_key" UNIQUE ("stripe_customer_id")`);
        await queryRunner.query(`ALTER TABLE "billing"."billing_webhook_events" ADD CONSTRAINT "billing_webhook_events_stripe_event_id_key" UNIQUE ("stripe_event_id")`);
        await queryRunner.query(`ALTER TABLE "core"."hormone_logs" ALTER COLUMN "date_taken" SET DEFAULT CURRENT_DATE`);
        await queryRunner.query(`DELETE FROM "typeorm_metadata" WHERE "type" = $1 AND "name" = $2 AND "database" = $3 AND "schema" = $4 AND "table" = $5`, ["GENERATED_COLUMN","coordinates","postgres","core","stores"]);
        await queryRunner.query(`ALTER TABLE "core"."stores" DROP COLUMN "coordinates"`);
        await queryRunner.query(`INSERT INTO "typeorm_metadata"("database", "schema", "table", "type", "name", "value") VALUES ($1, $2, $3, $4, $5, $6)`, ["postgres","core","stores","GENERATED_COLUMN","coordinates",""]);
        await queryRunner.query(`ALTER TABLE "core"."stores" ADD "coordinates" geography(Point,4326)`);
        await queryRunner.query(`ALTER TABLE "core"."products" DROP COLUMN "billing_quantity"`);
        await queryRunner.query(`ALTER TABLE "core"."products" DROP COLUMN "billing_interval"`);
        await queryRunner.query(`ALTER TABLE "core"."products" DROP COLUMN "billing_type"`);
        await queryRunner.query(`ALTER TABLE "core"."products" DROP COLUMN "form_factor"`);
        await queryRunner.query(`ALTER TABLE "core"."products" DROP COLUMN "unit_count_type"`);
        await queryRunner.query(`ALTER TABLE "core"."products" DROP COLUMN "unit_count"`);
        await queryRunner.query(`ALTER TABLE "analytics"."analytics_events" ADD CONSTRAINT "analytics_events_type_check" CHECK ((type = ANY (ARRAY['page_view'::text, 'click_through'::text, 'product_view'::text])))`);
        await queryRunner.query(`ALTER TABLE "billing"."billing_subscriptions" ADD CONSTRAINT "billing_subscriptions_status_check" CHECK ((status = ANY (ARRAY['incomplete'::text, 'incomplete_expired'::text, 'trialing'::text, 'active'::text, 'past_due'::text, 'canceled'::text, 'unpaid'::text, 'paused'::text])))`);
        await queryRunner.query(`ALTER TABLE "billing"."billing_plans" ADD CONSTRAINT "billing_plans_interval_check" CHECK (("interval" = ANY (ARRAY['month'::text, 'year'::text])))`);
        await queryRunner.query(`ALTER TABLE "core"."hormone_logs" ADD CONSTRAINT "hormone_logs_mood_score_check" CHECK (((mood_score >= 1) AND (mood_score <= 5)))`);
        await queryRunner.query(`ALTER TABLE "core"."hormone_logs" ADD CONSTRAINT "hormone_logs_form_factor_check" CHECK ((form_factor = ANY (ARRAY['injection'::text, 'gel'::text, 'cream'::text, 'oral'::text, 'patch'::text, 'pellet'::text, 'nasal'::text, 'other'::text])))`);
        await queryRunner.query(`ALTER TABLE "core"."reviews" ADD CONSTRAINT "reviews_rating_check" CHECK (((rating >= 1) AND (rating <= 5)))`);
        await queryRunner.query(`CREATE INDEX "idx_analytics_events_type_date" ON "analytics"."analytics_events" ("occurred_at", "type") `);
        await queryRunner.query(`CREATE INDEX "idx_analytics_events_vendor_date" ON "analytics"."analytics_events" ("occurred_at", "vendor_id") `);
        await queryRunner.query(`CREATE INDEX "idx_analytics_events_store_date" ON "analytics"."analytics_events" ("occurred_at", "store_id") `);
        await queryRunner.query(`CREATE INDEX "idx_billing_subscriptions_billing_customer_id" ON "billing"."billing_subscriptions" ("billing_customer_id") `);
        await queryRunner.query(`CREATE INDEX "idx_billing_subscriptions_plan_id" ON "billing"."billing_subscriptions" ("plan_id") `);
        await queryRunner.query(`CREATE INDEX "idx_billing_subscriptions_vendor_id" ON "billing"."billing_subscriptions" ("vendor_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_billing_subscription_items_subscription_price" ON "billing"."billing_subscription_items" ("billing_subscription_id", "stripe_price_id") `);
        await queryRunner.query(`CREATE INDEX "idx_billing_subscription_items_vendor_id" ON "billing"."billing_subscription_items" ("vendor_id") `);
        await queryRunner.query(`CREATE INDEX "idx_billing_subscription_items_price_id" ON "billing"."billing_subscription_items" ("stripe_price_id") `);
        await queryRunner.query(`CREATE INDEX "idx_billing_subscription_items_subscription_id" ON "billing"."billing_subscription_items" ("billing_subscription_id") `);
        await queryRunner.query(`CREATE INDEX "idx_billing_invoices_subscription_id" ON "billing"."billing_invoices" ("billing_subscription_id") `);
        await queryRunner.query(`CREATE INDEX "idx_billing_invoices_vendor_id" ON "billing"."billing_invoices" ("vendor_id") `);
        await queryRunner.query(`CREATE INDEX "idx_billing_customers_vendor_id" ON "billing"."billing_customers" ("vendor_id") `);
        await queryRunner.query(`CREATE INDEX "idx_billing_webhook_events_type" ON "billing"."billing_webhook_events" ("type") `);
        await queryRunner.query(`CREATE INDEX "idx_hormone_logs_profile_date" ON "core"."hormone_logs" ("customer_profile_id", "date_taken") `);
        await queryRunner.query(`CREATE INDEX "idx_stores_coordinates_gix" ON "core"."stores" USING GiST ("coordinates") WHERE (coordinates IS NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "idx_reviews_status" ON "core"."reviews" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_reviews_store_id" ON "core"."reviews" ("store_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_reviews_store_user" ON "core"."reviews" ("store_id", "user_id") WHERE (deleted_at IS NULL)`);
        await queryRunner.query(`ALTER TABLE "core"."review_tag_links" ADD CONSTRAINT "review_tag_links_tag_id_fkey" FOREIGN KEY ("tag_id") REFERENCES "core"."review_tags"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."review_tag_links" ADD CONSTRAINT "review_tag_links_review_id_fkey" FOREIGN KEY ("review_id") REFERENCES "core"."reviews"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."product_category_links" ADD CONSTRAINT "product_category_links_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "core"."products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."product_category_links" ADD CONSTRAINT "product_category_links_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "core"."product_categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "analytics"."analytics_events" ADD CONSTRAINT "analytics_events_vendor_id_fkey" FOREIGN KEY ("vendor_id") REFERENCES "core"."vendors"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "analytics"."analytics_events" ADD CONSTRAINT "analytics_events_store_id_fkey" FOREIGN KEY ("store_id") REFERENCES "core"."stores"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "analytics"."analytics_events" ADD CONSTRAINT "analytics_events_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "core"."products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "billing"."billing_subscriptions" ADD CONSTRAINT "billing_subscriptions_vendor_id_fkey" FOREIGN KEY ("vendor_id") REFERENCES "core"."vendors"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "billing"."billing_subscriptions" ADD CONSTRAINT "billing_subscriptions_plan_id_fkey" FOREIGN KEY ("plan_id") REFERENCES "billing"."billing_plans"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "billing"."billing_subscriptions" ADD CONSTRAINT "billing_subscriptions_billing_customer_id_fkey" FOREIGN KEY ("billing_customer_id") REFERENCES "billing"."billing_customers"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "billing"."billing_subscription_items" ADD CONSTRAINT "billing_subscription_items_vendor_id_fkey" FOREIGN KEY ("vendor_id") REFERENCES "core"."vendors"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "billing"."billing_subscription_items" ADD CONSTRAINT "billing_subscription_items_billing_subscription_id_fkey" FOREIGN KEY ("billing_subscription_id") REFERENCES "billing"."billing_subscriptions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "billing"."billing_invoices" ADD CONSTRAINT "billing_invoices_vendor_id_fkey" FOREIGN KEY ("vendor_id") REFERENCES "core"."vendors"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "billing"."billing_invoices" ADD CONSTRAINT "billing_invoices_billing_subscription_id_fkey" FOREIGN KEY ("billing_subscription_id") REFERENCES "billing"."billing_subscriptions"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "billing"."billing_customers" ADD CONSTRAINT "billing_customers_vendor_id_fkey" FOREIGN KEY ("vendor_id") REFERENCES "core"."vendors"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."hormone_logs" ADD CONSTRAINT "hormone_logs_customer_profile_id_fkey" FOREIGN KEY ("customer_profile_id") REFERENCES "core"."customer_profiles"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."reviews" ADD CONSTRAINT "reviews_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."reviews" ADD CONSTRAINT "reviews_store_id_fkey" FOREIGN KEY ("store_id") REFERENCES "core"."stores"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."favorite_stores" ADD CONSTRAINT "FK_favorite_store_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."customer_profiles" ADD CONSTRAINT "customer_profiles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
